# Generated by Django 5.0.6 on 2024-07-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_turf'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='kit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
