# Generated by Django 5.0.6 on 2024-07-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_jersey_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballaccessory',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
