# Generated by Django 5.0.6 on 2024-07-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_footballaccessory_color_turf_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
