# Generated by Django 5.0.6 on 2024-07-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_jersey_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballaccessory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jersey',
            name='description',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='description',
        ),
    ]
