# Generated by Django 5.0.6 on 2024-07-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myTeam', models.CharField(default=None, max_length=100, null=True)),
                ('opponent', models.CharField(default=None, max_length=100)),
                ('date', models.DateTimeField(default=None)),
                ('location', models.CharField(default=None, max_length=200)),
                ('type', models.CharField(default=None, max_length=100)),
                ('match', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(null=True)),
                ('kit', models.IntegerField(unique=True)),
                ('position', models.CharField(choices=[('goalkeeper', 'Goalkeeper'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('forward', 'Forward')], default='midfielder', max_length=50)),
                ('age', models.IntegerField()),
                ('team', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('img', models.ImageField(upload_to='player_images/')),
                ('nationality', models.CharField(max_length=100, null=True)),
                ('nationality_image', models.ImageField(null=True, upload_to='player_nationality_images/')),
            ],
        ),
    ]
