# Generated by Django 5.0.6 on 2024-07-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='name',
        ),
        migrations.AddField(
            model_name='fixture',
            name='match',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='fixture',
            name='opponent',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='location',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
